/**
 * Serialize the Lean-shaped projection of spec/kernel.json into
 * proofs/KernelIR.lean: a `Mneme.Kernel` literal plus the static
 * `Mneme.Certificate` proved `by decide` (ADR-008, ADR-014 — the pure
 * `decide` term is the artifact; native_decide is not).
 *
 * The emitted file is committed so the proofs job needs no Bun; the
 * judge test suite regenerates it and fails on any byte drift. Run:
 *
 *   bun src/lean-export.ts          # rewrites ../proofs/KernelIR.lean
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { dirname, resolve } from "node:path";
import { loadKernel } from "./kernel.js";
import { projectKernel, type LeanKernel } from "./lean-kernel.js";

const HERE = dirname(fileURLToPath(import.meta.url));
export const KERNEL_IR_LEAN_PATH = resolve(HERE, "../../proofs/KernelIR.lean");

/** Lean string literal. The IR carries no control characters; refuse any. */
function str(s: string): string {
  for (const ch of s) {
    const c = ch.codePointAt(0)!;
    if (c < 0x20 || c === 0x7f) {
      throw new Error(`control character in IR string: ${JSON.stringify(s)}`);
    }
  }
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function strList(xs: string[]): string {
  return `[${xs.map(str).join(", ")}]`;
}

/** The 19 static invariants of inhabitants.md resolve to these 17 conjuncts
 *  of `Mneme.Laws` (INV-G4-VERSIONED and INV-LAYERS-FOUR are sub-predicates
 *  of `WellFormed`). Order matches the conjunction in spec/lean/Laws.lean. */
const LAW_CONJUNCTS: [theorem: string, prop: string][] = [
  ["kernel_wellFormed", "WellFormed"],
  ["kernel_frozenTransforms", "FrozenTransforms"],
  ["kernel_structuralIsTransform", "StructuralIsTransform"],
  ["kernel_hybridDeclared", "HybridDeclared"],
  ["kernel_authorNotCore", "AuthorNotCore"],
  ["kernel_hasSelfAndAuth", "HasSelfAndAuth"],
  ["kernel_capTokenPort", "CapTokenPort"],
  ["kernel_twinOrigin", "TwinOrigin"],
  ["kernel_hasActionGate", "HasActionGate"],
  ["kernel_partitionProposeNoInstall", "PartitionProposeNoInstall"],
  ["kernel_reindexNoSpec", "ReindexNoSpec"],
  ["kernel_bindIntersectsTokens", "BindIntersectsTokens"],
  ["kernel_archiveKeepsLosers", "ArchiveKeepsLosers"],
  ["kernel_evalHidden", "EvalHidden"],
  ["kernel_cutClassify", "CutClassify"],
  ["kernel_portRoutable", "PortRoutable"],
  ["kernel_auditNotGate", "AuditNotGate"],
];

export function renderKernelIR(k: LeanKernel): string {
  const out: string[] = [];
  const push = (line: string): void => {
    out.push(line);
  };

  push("-- GENERATED by `cd helix && bun src/lean-export.ts` from spec/kernel.json.");
  push("-- Do not edit by hand; helix/test/judge.spec.ts enforces byte parity.");
  push("--");
  push("-- Projection of the mneme.spec/0.10 kernel IR onto `Mneme.Kernel`:");
  push("-- ids, kinds, ports, edges, twins, frozen, layers. Prompt bodies are");
  push("-- not in the IR and are not here (G2). IR fields with no Lean");
  push("-- counterpart are dropped: node labels/roles/signatures/bodyHash/");
  push("-- promptRefs, edge `xor` (the exclusive-routing marker on pg-adl's");
  push("-- a3/a4 and a6/a7 pairs — this certificate is blind to it), graph");
  push("-- code/purpose/state/runtime, ingress, fuel, artifact metadata beyond");
  push("-- `version`, layer idx/name, twin `never` prose, and the audit policy.");
  push("--");
  push("-- `certificate` below is the STATIC gate only: IR-certified, not");
  push("-- MNEME-complete (ADR-008). RuntimeCertificate needs a real trace.");
  push("import Mneme.Kernel");
  push("import Mneme.WellFormed");
  push("import Mneme.Laws");
  push("import Mneme.Certified");
  push("");
  push("namespace KernelIR");
  push("open Mneme");
  push("");
  push("def kernel : Kernel := {");
  push(`  spec := ${str(k.spec)}`);

  push("  layers := [");
  k.layers.forEach((l, i) => {
    const comma = i < k.layers.length - 1 ? "," : "";
    push(
      `    { id := ${str(l.id)}, stores := ${strList(l.stores)}, graphIds := ${strList(l.graphIds)} }${comma}`,
    );
  });
  push("  ]");

  push("  graphs := [");
  k.graphs.forEach((g, gi) => {
    push(`    { id := ${str(g.id)}`);
    push("      nodes := [");
    g.nodes.forEach((n, ni) => {
      const comma = ni < g.nodes.length - 1 ? "," : "";
      const ports = n.ports
        .map(
          (p) =>
            `{ name := ${str(p.name)}, type := ${str(p.type)}, dir := ${p.dir === "in" ? ".«in»" : ".out"} }`,
        )
        .join(",\n            ");
      push(`        { id := ${str(n.id)}, kind := .${n.kind},`);
      push(`          ports := [${ports}] }${comma}`);
    });
    push("      ]");
    push("      edges := [");
    g.edges.forEach((e, ei) => {
      const comma = ei < g.edges.length - 1 ? "," : "";
      push(
        `        { id := ${str(e.id)}, «from» := ${str(e.from)}, to := ${str(e.to)},`,
      );
      push(
        `          fromPort := ${str(e.fromPort)}, toPort := ${str(e.toPort)}, kind := .${e.kind},`,
      );
      push(
        `          cyclic := ${e.cyclic}, guard := ${str(e.guard)} }${comma}`,
      );
    });
    push("      ]");
    push(
      `      version := ${str(g.version)} }${gi < k.graphs.length - 1 ? "," : ""}`,
    );
  });
  push("  ]");

  push("  twins := [");
  k.twins.forEach((t, i) => {
    const comma = i < k.twins.length - 1 ? "," : "";
    push(`    { id := ${str(t.id)}, origin := .${t.origin} }${comma}`);
  });
  push("  ]");
  push(`  frozen := ${strList(k.frozen)}`);
  push("}");
  push("");
  push("/-! Each conjunct of `Mneme.Laws` decided separately, then assembled.");
  push("    Pure `by decide` throughout — `native_decide` is a fast path, not");
  push("    the artifact (ADR-014). `kernel_wellFormed` needs `decide +kernel`:");
  push("    `versioned` compares `String.Slice`s (v4.33.1 `String.take`), which");
  push("    the elaborator cannot reduce; the trusted kernel can. The proof");
  push("    term is the same `of_decide_eq_true (Eq.refl true)` shape either");
  push("    way — no native code, no `Lean.ofReduceBool`. -/");
  push("");
  for (const [thm, prop] of LAW_CONJUNCTS) {
    const cfg = thm === "kernel_wellFormed" ? " +kernel" : "";
    push(`theorem ${thm} : ${prop} kernel := by decide${cfg}`);
  }
  push("");
  push("theorem kernel_laws : Laws kernel :=");
  const names = LAW_CONJUNCTS.map(([thm]) => thm);
  push(`  ⟨${names.join(",\n   ")}⟩`);
  push("");
  push("/-- The static certificate: IR-certified, not MNEME-complete. -/");
  push("def certificate : Certificate := ⟨kernel, kernel_laws⟩");
  push("");
  push("/- Axiom guard (ADR-014): fail the build if `sorryAx` or");
  push("   `Lean.ofReduceBool` (native_decide) ever appears. `propext` is the");
  push("   core axiom `decide` proofs carry on this toolchain (see CLAUDE.md,");
  push("   toolchain note). `Classical.choice` and `Quot.sound` enter through");
  push("   the v4.33.1 `String.Slice` machinery that `versioned`'s Decidable");
  push("   instance is *defined* with — they come from the toolchain's String");
  push("   library, not from the tactic, and appear for any theorem whose");
  push("   statement mentions `WellFormed`. The trace-law theorems in");
  push("   Regressions.lean stay at [propext]. -/");
  push(
    "/-- info: 'KernelIR.kernel_laws' depends on axioms: [propext, Classical.choice, Quot.sound] -/",
  );
  push("#guard_msgs in #print axioms kernel_laws");
  push("");
  push("end KernelIR");
  return out.join("\n") + "\n";
}

export function writeKernelIR(path: string = KERNEL_IR_LEAN_PATH): string {
  const text = renderKernelIR(projectKernel(loadKernel()));
  writeFileSync(path, text);
  return path;
}

if (
  process.argv[1] &&
  import.meta.url === pathToFileURL(resolve(process.argv[1])).href
) {
  const path = writeKernelIR();
  console.log(`wrote ${path}`);
}
