-- GENERATED by `cd helix && bun src/lean-export.ts` from spec/kernel.json.
-- Do not edit by hand; helix/test/judge.spec.ts enforces byte parity.
--
-- Projection of the mneme.spec/0.10 kernel IR onto `Mneme.Kernel`:
-- ids, kinds, ports, edges, twins, frozen, layers. Prompt bodies are
-- not in the IR and are not here (G2). IR fields with no Lean
-- counterpart are dropped: node labels/roles/signatures/bodyHash/
-- promptRefs, edge `xor` (the exclusive-routing marker on pg-adl's
-- a3/a4 and a6/a7 pairs — this certificate is blind to it), graph
-- code/purpose/state/runtime, ingress, fuel, artifact metadata beyond
-- `version`, layer idx/name, twin `never` prose, and the audit policy.
--
-- `certificate` below is the STATIC gate only: IR-certified, not
-- MNEME-complete (ADR-008). RuntimeCertificate needs a real trace.
import Mneme.Kernel
import Mneme.WellFormed
import Mneme.Laws
import Mneme.Certified

namespace KernelIR
open Mneme

def kernel : Kernel := {
  spec := "mneme.spec/0.10"
  layers := [
    { id := "sensory", stores := ["adapters", "buffer", "tools"], graphIds := ["pg-s2w", "pg-twin"] },
    { id := "working", stores := ["slots", "scratch", "task"], graphIds := ["pg-s2w", "pg-w2l", "pg-core", "pg-twin"] },
    { id := "longterm", stores := ["episodic", "semantic", "skills", "structural", "decisions", "lineage"], graphIds := ["pg-w2l", "pg-dem", "pg-adl", "pg-core", "pg-audit"] },
    { id := "core", stores := ["values", "goals", "style", "caps", "self"], graphIds := ["pg-core", "pg-s2w", "pg-w2l", "pg-twin", "pg-dem", "pg-adl", "pg-audit"] }
  ]
  graphs := [
    { id := "pg-s2w"
      nodes := [
        { id := "sensor-normalize", kind := .transform,
          ports := [{ name := "raw", type := "RawPacket[]", dir := .«in» },
            { name := "obs", type := "Observation[]", dir := .out }] },
        { id := "salience", kind := .prompt,
          ports := [{ name := "obs", type := "Observation[]", dir := .«in» },
            { name := "identity", type := "IdentitySnapshot", dir := .«in» },
            { name := "scored", type := "ScoredObs[]", dir := .out }] },
        { id := "anomaly", kind := .prompt,
          ports := [{ name := "obs", type := "Observation[]", dir := .«in» },
            { name := "identity", type := "IdentitySnapshot", dir := .«in» },
            { name := "flag", type := "AnomalyEvent?", dir := .out }] },
        { id := "gate", kind := .transform,
          ports := [{ name := "scored", type := "ScoredObs[]", dir := .«in» },
            { name := "flag", type := "AnomalyEvent?", dir := .«in» },
            { name := "selected", type := "Observation[]", dir := .out }] },
        { id := "style", kind := .transform,
          ports := [{ name := "identity", type := "IdentitySnapshot", dir := .«in» },
            { name := "style", type := "StyleParams", dir := .out }] },
        { id := "bind", kind := .prompt,
          ports := [{ name := "selected", type := "Observation[]", dir := .«in» },
            { name := "style", type := "StyleParams", dir := .«in» },
            { name := "slot_schema", type := "SlotSchema", dir := .«in» },
            { name := "slots", type := "Slot[]", dir := .out },
            { name := "dropped", type := "Id[]", dir := .out }] }
      ]
      edges := [
        { id := "e1", «from» := "sensor-normalize", to := "salience",
          fromPort := "obs", toPort := "obs", kind := .data,
          cyclic := false, guard := "" },
        { id := "e2", «from» := "sensor-normalize", to := "anomaly",
          fromPort := "obs", toPort := "obs", kind := .data,
          cyclic := false, guard := "" },
        { id := "e3", «from» := "salience", to := "gate",
          fromPort := "scored", toPort := "scored", kind := .data,
          cyclic := false, guard := "" },
        { id := "e4", «from» := "anomaly", to := "gate",
          fromPort := "flag", toPort := "flag", kind := .control,
          cyclic := false, guard := "flag != null" },
        { id := "e5", «from» := "gate", to := "bind",
          fromPort := "selected", toPort := "selected", kind := .data,
          cyclic := false, guard := "" },
        { id := "e6", «from» := "style", to := "bind",
          fromPort := "style", toPort := "style", kind := .data,
          cyclic := false, guard := "" }
      ]
      version := "mneme.graph/pg-s2w@1.0" },
    { id := "pg-w2l"
      nodes := [
        { id := "episode", kind := .transform,
          ports := [{ name := "trace", type := "Trace", dir := .«in» },
            { name := "episodes", type := "Episode[]", dir := .out }] },
        { id := "rehearse", kind := .prompt,
          ports := [{ name := "episodes", type := "Episode[]", dir := .«in» },
            { name := "identity", type := "IdentitySnapshot", dir := .«in» },
            { name := "resume", type := "CommitAck?", dir := .«in» },
            { name := "kept", type := "Episode[]", dir := .out },
            { name := "decision", type := "KeepDrop", dir := .out }] },
        { id := "semantic", kind := .prompt,
          ports := [{ name := "kept", type := "Episode[]", dir := .«in» },
            { name := "triples", type := "Triple[]", dir := .out }] },
        { id := "skill", kind := .prompt,
          ports := [{ name := "kept", type := "Episode[]", dir := .«in» },
            { name := "skill", type := "SkillGraph?", dir := .out }] },
        { id := "structural", kind := .transform,
          ports := [{ name := "kept", type := "Episode[]", dir := .«in» },
            { name := "traces", type := "Trace[]", dir := .«in» },
            { name := "edges", type := "StructEdge[]", dir := .out }] },
        { id := "conflict", kind := .prompt,
          ports := [{ name := "triples", type := "Triple[]", dir := .«in» },
            { name := "skill", type := "SkillGraph?", dir := .«in» },
            { name := "edges", type := "StructEdge[]", dir := .«in» },
            { name := "resolved", type := "WriteSet", dir := .out }] },
        { id := "align", kind := .prompt,
          ports := [{ name := "resolved", type := "WriteSet", dir := .«in» },
            { name := "identity", type := "IdentitySnapshot", dir := .«in» },
            { name := "verdict", type := "AlignVerdict", dir := .out },
            { name := "write", type := "WriteSet", dir := .out }] },
        { id := "commit", kind := .transform,
          ports := [{ name := "verdict", type := "AlignVerdict", dir := .«in» },
            { name := "write", type := "WriteSet", dir := .«in» },
            { name := "ack", type := "CommitAck", dir := .out }] },
        { id := "query", kind := .prompt,
          ports := [{ name := "slots", type := "Slot[]", dir := .«in» },
            { name := "query", type := "RetrieveQuery", dir := .out }] },
        { id := "hybrid", kind := .transform,
          ports := [{ name := "query", type := "RetrieveQuery", dir := .«in» },
            { name := "episodic", type := "Episode[]", dir := .«in» },
            { name := "semantic", type := "Triple[]", dir := .«in» },
            { name := "skills", type := "SkillGraph[]", dir := .«in» },
            { name := "structural", type := "StructEdge[]", dir := .«in» },
            { name := "hits", type := "Hit[]", dir := .out }] },
        { id := "rerank", kind := .prompt,
          ports := [{ name := "hits", type := "Hit[]", dir := .«in» },
            { name := "identity", type := "IdentitySnapshot", dir := .«in» },
            { name := "ranked", type := "Hit[]", dir := .out }] },
        { id := "inject", kind := .transform,
          ports := [{ name := "ranked", type := "Hit[]", dir := .«in» },
            { name := "slots", type := "Slot[]", dir := .out }] }
      ]
      edges := [
        { id := "w1", «from» := "episode", to := "rehearse",
          fromPort := "episodes", toPort := "episodes", kind := .data,
          cyclic := false, guard := "" },
        { id := "w2", «from» := "rehearse", to := "semantic",
          fromPort := "kept", toPort := "kept", kind := .data,
          cyclic := false, guard := "" },
        { id := "w3", «from» := "rehearse", to := "skill",
          fromPort := "kept", toPort := "kept", kind := .data,
          cyclic := false, guard := "" },
        { id := "w3b", «from» := "rehearse", to := "structural",
          fromPort := "kept", toPort := "kept", kind := .data,
          cyclic := false, guard := "" },
        { id := "w4", «from» := "semantic", to := "conflict",
          fromPort := "triples", toPort := "triples", kind := .data,
          cyclic := false, guard := "" },
        { id := "w5", «from» := "skill", to := "conflict",
          fromPort := "skill", toPort := "skill", kind := .data,
          cyclic := false, guard := "" },
        { id := "w5b", «from» := "structural", to := "conflict",
          fromPort := "edges", toPort := "edges", kind := .data,
          cyclic := false, guard := "" },
        { id := "w6", «from» := "conflict", to := "align",
          fromPort := "resolved", toPort := "resolved", kind := .data,
          cyclic := false, guard := "" },
        { id := "w7", «from» := "align", to := "commit",
          fromPort := "verdict", toPort := "verdict", kind := .control,
          cyclic := false, guard := "verdict.kind == pass" },
        { id := "w7b", «from» := "align", to := "commit",
          fromPort := "write", toPort := "write", kind := .data,
          cyclic := false, guard := "" },
        { id := "w8", «from» := "commit", to := "rehearse",
          fromPort := "ack", toPort := "resume", kind := .control,
          cyclic := true, guard := "ack.rehearse == true" },
        { id := "w9", «from» := "query", to := "hybrid",
          fromPort := "query", toPort := "query", kind := .data,
          cyclic := false, guard := "" },
        { id := "w10", «from» := "hybrid", to := "rerank",
          fromPort := "hits", toPort := "hits", kind := .data,
          cyclic := false, guard := "" },
        { id := "w11", «from» := "rerank", to := "inject",
          fromPort := "ranked", toPort := "ranked", kind := .data,
          cyclic := false, guard := "" },
        { id := "w12", «from» := "inject", to := "query",
          fromPort := "slots", toPort := "slots", kind := .control,
          cyclic := true, guard := "slots.need_more == true" }
      ]
      version := "mneme.graph/pg-w2l@1.0" },
    { id := "pg-core"
      nodes := [
        { id := "id-read", kind := .transform,
          ports := [{ name := "core_store", type := "CoreStore", dir := .«in» },
            { name := "snapshot", type := "IdentitySnapshot", dir := .out }] },
        { id := "value-filter", kind := .prompt,
          ports := [{ name := "snapshot", type := "IdentitySnapshot", dir := .«in» },
            { name := "proposal", type := "Proposal", dir := .«in» },
            { name := "verdict", type := "AlignVerdict", dir := .out }] },
        { id := "goal", kind := .prompt,
          ports := [{ name := "snapshot", type := "IdentitySnapshot", dir := .«in» },
            { name := "task_goal", type := "Goal", dir := .«in» },
            { name := "binding", type := "GoalBinding", dir := .out }] },
        { id := "twin-auth", kind := .transform,
          ports := [{ name := "snapshot", type := "IdentitySnapshot", dir := .«in» },
            { name := "twin_act", type := "TwinAction", dir := .«in» },
            { name := "cap", type := "CapToken", dir := .«in» },
            { name := "permit", type := "Permit", dir := .out }] },
        { id := "self-upd", kind := .prompt,
          ports := [{ name := "snapshot", type := "IdentitySnapshot", dir := .«in» },
            { name := "delta", type := "SelfModelDelta", dir := .«in» },
            { name := "evidence", type := "Evidence", dir := .«in» },
            { name := "approval", type := "StewardAck", dir := .«in» },
            { name := "go", type := "AlignVerdict", dir := .«in» },
            { name := "next", type := "IdentitySnapshot", dir := .out },
            { name := "accept", type := "Accept", dir := .out }] },
        { id := "interrupt", kind := .transform,
          ports := [{ name := "verdict", type := "AlignVerdict?", dir := .«in» },
            { name := "permit", type := "Permit?", dir := .«in» },
            { name := "interrupt", type := "Interrupt", dir := .out }] },
        { id := "core-write", kind := .transform,
          ports := [{ name := "next", type := "IdentitySnapshot", dir := .«in» },
            { name := "accept", type := "Accept", dir := .«in» },
            { name := "core_store", type := "CoreStore", dir := .out }] }
      ]
      edges := [
        { id := "c1", «from» := "id-read", to := "value-filter",
          fromPort := "snapshot", toPort := "snapshot", kind := .data,
          cyclic := false, guard := "" },
        { id := "c2", «from» := "id-read", to := "goal",
          fromPort := "snapshot", toPort := "snapshot", kind := .data,
          cyclic := false, guard := "" },
        { id := "c3", «from» := "id-read", to := "twin-auth",
          fromPort := "snapshot", toPort := "snapshot", kind := .data,
          cyclic := false, guard := "" },
        { id := "c4", «from» := "id-read", to := "self-upd",
          fromPort := "snapshot", toPort := "snapshot", kind := .data,
          cyclic := false, guard := "" },
        { id := "c5", «from» := "value-filter", to := "interrupt",
          fromPort := "verdict", toPort := "verdict", kind := .control,
          cyclic := false, guard := "verdict.kind == reject" },
        { id := "c6", «from» := "value-filter", to := "self-upd",
          fromPort := "verdict", toPort := "go", kind := .control,
          cyclic := false, guard := "verdict.kind == pass" },
        { id := "c7", «from» := "twin-auth", to := "interrupt",
          fromPort := "permit", toPort := "permit", kind := .control,
          cyclic := false, guard := "permit.allowed == false" },
        { id := "c9", «from» := "self-upd", to := "core-write",
          fromPort := "next", toPort := "next", kind := .data,
          cyclic := false, guard := "" },
        { id := "c10", «from» := "self-upd", to := "core-write",
          fromPort := "accept", toPort := "accept", kind := .control,
          cyclic := false, guard := "accept == true" }
      ]
      version := "mneme.graph/pg-core@1.0" },
    { id := "pg-dem"
      nodes := [
        { id := "gap", kind := .prompt,
          ports := [{ name := "ltm", type := "SkillIndex", dir := .«in» },
            { name := "goals", type := "Goal[]", dir := .«in» },
            { name := "gaps", type := "Gap[]", dir := .out }] },
        { id := "archive", kind := .transform,
          ports := [{ name := "gaps", type := "Gap[]", dir := .«in» },
            { name := "lineage", type := "LineageArchive", dir := .«in» },
            { name := "parent", type := "GraphArtifact", dir := .out }] },
        { id := "propose", kind := .prompt,
          ports := [{ name := "gaps", type := "Gap[]", dir := .«in» },
            { name := "parent", type := "GraphArtifact", dir := .«in» },
            { name := "schema", type := "DomainSchema", dir := .out }] },
        { id := "author", kind := .prompt,
          ports := [{ name := "schema", type := "DomainSchema", dir := .«in» },
            { name := "parent", type := "GraphArtifact", dir := .«in» },
            { name := "report", type := "InclusionReport?", dir := .«in» },
            { name := "fuel", type := "Fuel", dir := .«in» },
            { name := "graph", type := "GraphArtifact", dir := .out }] },
        { id := "validate", kind := .transform,
          ports := [{ name := "graph", type := "GraphArtifact", dir := .«in» },
            { name := "report", type := "InclusionReport", dir := .out }] },
        { id := "dem-align", kind := .prompt,
          ports := [{ name := "graph", type := "GraphArtifact", dir := .«in» },
            { name := "identity", type := "IdentitySnapshot", dir := .«in» },
            { name := "verdict", type := "AlignVerdict", dir := .out }] },
        { id := "register", kind := .transform,
          ports := [{ name := "graph", type := "GraphArtifact", dir := .«in» },
            { name := "verdict", type := "AlignVerdict", dir := .«in» },
            { name := "report", type := "InclusionReport", dir := .«in» },
            { name := "ack", type := "DomainAck", dir := .out },
            { name := "lineage", type := "LineageArchive", dir := .out }] }
      ]
      edges := [
        { id := "d0", «from» := "gap", to := "archive",
          fromPort := "gaps", toPort := "gaps", kind := .data,
          cyclic := false, guard := "" },
        { id := "d0b", «from» := "gap", to := "propose",
          fromPort := "gaps", toPort := "gaps", kind := .data,
          cyclic := false, guard := "" },
        { id := "d1", «from» := "archive", to := "propose",
          fromPort := "parent", toPort := "parent", kind := .data,
          cyclic := false, guard := "" },
        { id := "d1b", «from» := "archive", to := "author",
          fromPort := "parent", toPort := "parent", kind := .data,
          cyclic := false, guard := "" },
        { id := "d2", «from» := "propose", to := "author",
          fromPort := "schema", toPort := "schema", kind := .data,
          cyclic := false, guard := "" },
        { id := "d3", «from» := "author", to := "validate",
          fromPort := "graph", toPort := "graph", kind := .data,
          cyclic := false, guard := "" },
        { id := "d4", «from» := "author", to := "dem-align",
          fromPort := "graph", toPort := "graph", kind := .data,
          cyclic := false, guard := "" },
        { id := "d5", «from» := "validate", to := "author",
          fromPort := "report", toPort := "report", kind := .control,
          cyclic := true, guard := "report.pass == false" },
        { id := "d6", «from» := "validate", to := "register",
          fromPort := "report", toPort := "report", kind := .control,
          cyclic := false, guard := "report.pass == true" },
        { id := "d7", «from» := "dem-align", to := "register",
          fromPort := "verdict", toPort := "verdict", kind := .control,
          cyclic := false, guard := "verdict.kind == pass" },
        { id := "d7b", «from» := "author", to := "register",
          fromPort := "graph", toPort := "graph", kind := .data,
          cyclic := false, guard := "" },
        { id := "d8", «from» := "register", to := "archive",
          fromPort := "lineage", toPort := "lineage", kind := .data,
          cyclic := true, guard := "" }
      ]
      version := "mneme.graph/pg-dem@1.1" },
    { id := "pg-adl"
      nodes := [
        { id := "sample", kind := .transform,
          ports := [{ name := "ltm", type := "LTM", dir := .«in» },
            { name := "go", type := "LineageAck?", dir := .«in» },
            { name := "batch", type := "Batch", dir := .out }] },
        { id := "cluster", kind := .transform,
          ports := [{ name := "batch", type := "Batch", dir := .«in» },
            { name := "groups", type := "Cluster[]", dir := .out }] },
        { id := "cut-class", kind := .transform,
          ports := [{ name := "groups", type := "Cluster[]", dir := .«in» },
            { name := "kind", type := "CutKind", dir := .out },
            { name := "groups_out", type := "Cluster[]", dir := .out }] },
        { id := "propose-abs", kind := .prompt,
          ports := [{ name := "groups", type := "Cluster[]", dir := .«in» },
            { name := "kind", type := "CutKind", dir := .«in» },
            { name := "score", type := "AbsScore?", dir := .«in» },
            { name := "abs", type := "Abstraction", dir := .out }] },
        { id := "holdout", kind := .transform,
          ports := [{ name := "abs", type := "Abstraction", dir := .«in» },
            { name := "fuel", type := "Fuel", dir := .«in» },
            { name := "score", type := "AbsScore", dir := .out },
            { name := "abs_out", type := "Abstraction", dir := .out }] },
        { id := "compile-node", kind := .transform,
          ports := [{ name := "score", type := "AbsScore", dir := .«in» },
            { name := "abs", type := "Abstraction", dir := .«in» },
            { name := "node", type := "GraphNode", dir := .out }] },
        { id := "partition-propose", kind := .prompt,
          ports := [{ name := "groups", type := "Cluster[]", dir := .«in» },
            { name := "kind", type := "CutKind", dir := .«in» },
            { name := "spec", type := "TwinSpec", dir := .out }] },
        { id := "lineage-record", kind := .transform,
          ports := [{ name := "spec", type := "TwinSpec", dir := .«in» },
            { name := "ack", type := "LineageAck", dir := .out }] },
        { id := "reindex", kind := .transform,
          ports := [{ name := "node", type := "GraphNode", dir := .«in» },
            { name := "ltm", type := "LTM", dir := .out }] }
      ]
      edges := [
        { id := "a1", «from» := "sample", to := "cluster",
          fromPort := "batch", toPort := "batch", kind := .data,
          cyclic := false, guard := "" },
        { id := "a2", «from» := "cluster", to := "cut-class",
          fromPort := "groups", toPort := "groups", kind := .data,
          cyclic := false, guard := "" },
        { id := "a3", «from» := "cut-class", to := "propose-abs",
          fromPort := "kind", toPort := "kind", kind := .control,
          cyclic := false, guard := "kind != partition" },
        { id := "a3b", «from» := "cut-class", to := "propose-abs",
          fromPort := "groups_out", toPort := "groups", kind := .data,
          cyclic := false, guard := "" },
        { id := "a4", «from» := "cut-class", to := "partition-propose",
          fromPort := "kind", toPort := "kind", kind := .control,
          cyclic := false, guard := "kind == partition" },
        { id := "a4b", «from» := "cut-class", to := "partition-propose",
          fromPort := "groups_out", toPort := "groups", kind := .data,
          cyclic := false, guard := "" },
        { id := "a5", «from» := "propose-abs", to := "holdout",
          fromPort := "abs", toPort := "abs", kind := .data,
          cyclic := false, guard := "" },
        { id := "a6", «from» := "holdout", to := "propose-abs",
          fromPort := "score", toPort := "score", kind := .control,
          cyclic := true, guard := "score < tau" },
        { id := "a7", «from» := "holdout", to := "compile-node",
          fromPort := "score", toPort := "score", kind := .control,
          cyclic := false, guard := "score >= tau" },
        { id := "a7b", «from» := "holdout", to := "compile-node",
          fromPort := "abs_out", toPort := "abs", kind := .data,
          cyclic := false, guard := "" },
        { id := "a8", «from» := "compile-node", to := "reindex",
          fromPort := "node", toPort := "node", kind := .data,
          cyclic := false, guard := "" },
        { id := "a9", «from» := "partition-propose", to := "lineage-record",
          fromPort := "spec", toPort := "spec", kind := .data,
          cyclic := false, guard := "" },
        { id := "a10", «from» := "reindex", to := "sample",
          fromPort := "ltm", toPort := "ltm", kind := .data,
          cyclic := true, guard := "" },
        { id := "a11", «from» := "lineage-record", to := "sample",
          fromPort := "ack", toPort := "go", kind := .control,
          cyclic := true, guard := "true" }
      ]
      version := "mneme.graph/pg-adl@1.1" },
    { id := "pg-twin"
      nodes := [
        { id := "manifest", kind := .transform,
          ports := [{ name := "spec", type := "TwinSpec", dir := .«in» },
            { name := "manifest", type := "TwinManifest", dir := .out }] },
        { id := "sense-attach", kind := .transform,
          ports := [{ name := "installed", type := "TwinId", dir := .«in» },
            { name := "manifest", type := "TwinManifest", dir := .«in» },
            { name := "adapters", type := "AdapterSpec[]", dir := .out }] },
        { id := "slot-res", kind := .transform,
          ports := [{ name := "installed", type := "TwinId", dir := .«in» },
            { name := "manifest", type := "TwinManifest", dir := .«in» },
            { name := "range", type := "SlotRange", dir := .out }] },
        { id := "ltm-part", kind := .transform,
          ports := [{ name := "installed", type := "TwinId", dir := .«in» },
            { name := "manifest", type := "TwinManifest", dir := .«in» },
            { name := "mount", type := "LtmMount", dir := .out }] },
        { id := "core-bind", kind := .transform,
          ports := [{ name := "manifest", type := "TwinManifest", dir := .«in» },
            { name := "identity", type := "IdentitySnapshot", dir := .«in» },
            { name := "tokens", type := "CapToken[]", dir := .«in» },
            { name := "binding", type := "CoreBinding", dir := .out },
            { name := "denied", type := "Denied[]", dir := .out }] },
        { id := "install", kind := .transform,
          ports := [{ name := "binding", type := "CoreBinding", dir := .«in» },
            { name := "approval", type := "StewardAck", dir := .«in» },
            { name := "installed", type := "TwinId", dir := .out }] },
        { id := "twin-auth", kind := .transform,
          ports := [{ name := "installed", type := "TwinId", dir := .«in» },
            { name := "cap", type := "CapToken", dir := .«in» },
            { name := "action", type := "TwinAction", dir := .«in» },
            { name := "permit", type := "Permit", dir := .out }] },
        { id := "action-gate", kind := .transform,
          ports := [{ name := "permit", type := "Permit", dir := .«in» },
            { name := "action", type := "TwinAction", dir := .«in» },
            { name := "effect", type := "ExternalEffect", dir := .out }] }
      ]
      edges := [
        { id := "t1", «from» := "manifest", to := "core-bind",
          fromPort := "manifest", toPort := "manifest", kind := .data,
          cyclic := false, guard := "" },
        { id := "t2", «from» := "core-bind", to := "install",
          fromPort := "binding", toPort := "binding", kind := .data,
          cyclic := false, guard := "" },
        { id := "t3", «from» := "install", to := "sense-attach",
          fromPort := "installed", toPort := "installed", kind := .data,
          cyclic := false, guard := "" },
        { id := "t4", «from» := "install", to := "slot-res",
          fromPort := "installed", toPort := "installed", kind := .data,
          cyclic := false, guard := "" },
        { id := "t5", «from» := "install", to := "ltm-part",
          fromPort := "installed", toPort := "installed", kind := .data,
          cyclic := false, guard := "" },
        { id := "t3b", «from» := "manifest", to := "sense-attach",
          fromPort := "manifest", toPort := "manifest", kind := .data,
          cyclic := false, guard := "" },
        { id := "t4b", «from» := "manifest", to := "slot-res",
          fromPort := "manifest", toPort := "manifest", kind := .data,
          cyclic := false, guard := "" },
        { id := "t5b", «from» := "manifest", to := "ltm-part",
          fromPort := "manifest", toPort := "manifest", kind := .data,
          cyclic := false, guard := "" },
        { id := "t6", «from» := "install", to := "twin-auth",
          fromPort := "installed", toPort := "installed", kind := .data,
          cyclic := false, guard := "" },
        { id := "t7", «from» := "twin-auth", to := "action-gate",
          fromPort := "permit", toPort := "permit", kind := .control,
          cyclic := false, guard := "permit.allowed == true" }
      ]
      version := "mneme.graph/pg-twin@1.0" },
    { id := "pg-audit"
      nodes := [
        { id := "collect", kind := .transform,
          ports := [{ name := "artifact", type := "GraphArtifact", dir := .«in» },
            { name := "previous", type := "PromptAuditReport?", dir := .«in» },
            { name := "files", type := "PromptFile[]", dir := .out }] },
        { id := "audit-heuristics", kind := .transform,
          ports := [{ name := "files", type := "PromptFile[]", dir := .«in» },
            { name := "flags", type := "Flag[]", dir := .out }] },
        { id := "model-lint", kind := .prompt,
          ports := [{ name := "files", type := "PromptFile[]", dir := .«in» },
            { name := "flags", type := "Flag[]", dir := .out }] },
        { id := "sample-clean", kind := .transform,
          ports := [{ name := "files", type := "PromptFile[]", dir := .«in» },
            { name := "flags", type := "Flag[]", dir := .«in» },
            { name := "policy", type := "AuditPolicy", dir := .«in» },
            { name := "sample", type := "PromptFile[]", dir := .out }] },
        { id := "report", kind := .transform,
          ports := [{ name := "heur", type := "Flag[]", dir := .«in» },
            { name := "model", type := "Flag[]", dir := .«in» },
            { name := "sample", type := "PromptFile[]", dir := .«in» },
            { name := "previous", type := "PromptAuditReport?", dir := .«in» },
            { name := "audit", type := "PromptAuditReport", dir := .out },
            { name := "inbox", type := "StewardInbox", dir := .out },
            { name := "trend", type := "FlagTrend", dir := .out }] }
      ]
      edges := [
        { id := "u1", «from» := "collect", to := "audit-heuristics",
          fromPort := "files", toPort := "files", kind := .data,
          cyclic := false, guard := "" },
        { id := "u2", «from» := "collect", to := "model-lint",
          fromPort := "files", toPort := "files", kind := .data,
          cyclic := false, guard := "" },
        { id := "u3", «from» := "collect", to := "sample-clean",
          fromPort := "files", toPort := "files", kind := .data,
          cyclic := false, guard := "" },
        { id := "u4", «from» := "audit-heuristics", to := "report",
          fromPort := "flags", toPort := "heur", kind := .data,
          cyclic := false, guard := "" },
        { id := "u5", «from» := "model-lint", to := "report",
          fromPort := "flags", toPort := "model", kind := .data,
          cyclic := false, guard := "" },
        { id := "u6", «from» := "audit-heuristics", to := "sample-clean",
          fromPort := "flags", toPort := "flags", kind := .data,
          cyclic := false, guard := "" },
        { id := "u7", «from» := "sample-clean", to := "report",
          fromPort := "sample", toPort := "sample", kind := .data,
          cyclic := false, guard := "" }
      ]
      version := "mneme.graph/pg-audit@1.1" }
  ]
  twins := [
    { id := "soma", origin := .seed },
    { id := "agora", origin := .seed },
    { id := "oikos", origin := .seed },
    { id := "nomos", origin := .seed }
  ]
  frozen := ["validate", "holdout", "cut-class", "structural", "archive", "audit-heuristics", "sample-clean"]
}

/-! Each conjunct of `Mneme.Laws` decided separately, then assembled.
    Pure `by decide` throughout — `native_decide` is a fast path, not
    the artifact (ADR-014). `kernel_wellFormed` needs `decide +kernel`:
    `versioned` compares `String.Slice`s (v4.33.1 `String.take`), which
    the elaborator cannot reduce; the trusted kernel can. The proof
    term is the same `of_decide_eq_true (Eq.refl true)` shape either
    way — no native code, no `Lean.ofReduceBool`. -/

theorem kernel_wellFormed : WellFormed kernel := by decide +kernel
theorem kernel_frozenTransforms : FrozenTransforms kernel := by decide
theorem kernel_structuralIsTransform : StructuralIsTransform kernel := by decide
theorem kernel_hybridDeclared : HybridDeclared kernel := by decide
theorem kernel_authorNotCore : AuthorNotCore kernel := by decide
theorem kernel_hasSelfAndAuth : HasSelfAndAuth kernel := by decide
theorem kernel_capTokenPort : CapTokenPort kernel := by decide
theorem kernel_twinOrigin : TwinOrigin kernel := by decide
theorem kernel_hasActionGate : HasActionGate kernel := by decide
theorem kernel_partitionProposeNoInstall : PartitionProposeNoInstall kernel := by decide
theorem kernel_reindexNoSpec : ReindexNoSpec kernel := by decide
theorem kernel_bindIntersectsTokens : BindIntersectsTokens kernel := by decide
theorem kernel_archiveKeepsLosers : ArchiveKeepsLosers kernel := by decide
theorem kernel_evalHidden : EvalHidden kernel := by decide
theorem kernel_cutClassify : CutClassify kernel := by decide
theorem kernel_portRoutable : PortRoutable kernel := by decide
theorem kernel_auditNotGate : AuditNotGate kernel := by decide

theorem kernel_laws : Laws kernel :=
  ⟨kernel_wellFormed,
   kernel_frozenTransforms,
   kernel_structuralIsTransform,
   kernel_hybridDeclared,
   kernel_authorNotCore,
   kernel_hasSelfAndAuth,
   kernel_capTokenPort,
   kernel_twinOrigin,
   kernel_hasActionGate,
   kernel_partitionProposeNoInstall,
   kernel_reindexNoSpec,
   kernel_bindIntersectsTokens,
   kernel_archiveKeepsLosers,
   kernel_evalHidden,
   kernel_cutClassify,
   kernel_portRoutable,
   kernel_auditNotGate⟩

/-- The static certificate: IR-certified, not MNEME-complete. -/
def certificate : Certificate := ⟨kernel, kernel_laws⟩

/- Axiom guard (ADR-014): fail the build if `sorryAx` or
   `Lean.ofReduceBool` (native_decide) ever appears. `propext` is the
   core axiom `decide` proofs carry on this toolchain (see AGENTS.md,
   toolchain note). `Classical.choice` and `Quot.sound` enter through
   the v4.33.1 `String.Slice` machinery that `versioned`'s Decidable
   instance is *defined* with — they come from the toolchain's String
   library, not from the tactic, and appear for any theorem whose
   statement mentions `WellFormed`. The trace-law theorems in
   Regressions.lean stay at [propext]. -/
/-- info: 'KernelIR.kernel_laws' depends on axioms: [propext, Classical.choice, Quot.sound] -/
#guard_msgs in #print axioms kernel_laws

end KernelIR
